webmc/src/main/java/com/icesoft/faces/presenter/participant/LoginBean.java
/*
 * Version: MPL 1.1/GPL 2.0/LGPL 2.1
 *
 * "The contents of this file are subject to the Mozilla Public License
 * Version 1.1 (the "License"); you may not use this file except in
 * compliance with the License. You may obtain a copy of the License at
 * http://www.mozilla.org/MPL/
 *
 * Software distributed under the License is distributed on an "AS IS"
 * basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
 * License for the specific language governing rights and limitations under
 * the License.
 *
 * The Original Code is ICEfaces 1.5 open source software code, released
 * November 5, 2006. The Initial Developer of the Original Code is ICEsoft
 * Technologies Canada, Corp. Portions created by ICEsoft are Copyright (C)
 * 2004-2006 ICEsoft Technologies Canada, Corp. All Rights Reserved.
 *
 * Contributor(s): _____________________.
 *
 * Alternatively, the contents of this file may be used under the terms of
 * the GNU Lesser General Public License Version 2.1 or later (the "LGPL"
 * License), in which case the provisions of the LGPL License are
 * applicable instead of those above. If you wish to allow use of your
 * version of this file only under the terms of the LGPL License and not to
 * allow others to use your version of this file under the MPL, indicate
 * your decision by deleting the provisions above and replace them with
 * the notice and other provisions required by the LGPL License. If you do
 * not delete the provisions above, a recipient may use your version of
 * this file under either the MPL or the LGPL License."
 *
 */
package com.icesoft.faces.presenter.participant;

import javax.faces.component.UIComponent;
import javax.faces.component.UIInput;
import javax.faces.event.ActionEvent;
import javax.faces.event.ValueChangeEvent;

import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;

import com.icesoft.faces.component.ext.HtmlForm;
import com.icesoft.faces.component.ext.HtmlInputSecret;
import com.icesoft.faces.component.ext.HtmlInputText;
import com.icesoft.faces.presenter.presentation.PresentationManager;
import com.icesoft.faces.presenter.presentation.PresentationManagerBean;

/**
 * Class used to handle the login portion of a user's session.  This is done to
 * separate the main webmc functionality from the entire login process.
 */
public class LoginBean {
    private static Log log = LogFactory.getLog(LoginBean.class);

    private Participant parent;
    private String presentationName = "";
    private String presentationPassword;
    private HtmlInputText firstNameField = null;
    private boolean invalidPassword = false;
    private boolean invalidPresentation = false;
    
    public LoginBean(Participant parent) {
        this.parent = parent;
    }

    public Participant getParent() {
        return parent;
    }

    public void setParent(Participant parent) {
        this.parent = parent;
    }

    public String getPresentationName() {
        return presentationName;
    }

    public void setPresentationName(String presentationName) {
        this.presentationName = presentationName;
    }

    public String getPresentationPassword() {
        return presentationPassword;
    }

    public void setPresentationPassword(String presentationPassword) {
        this.presentationPassword = presentationPassword;
    }

    public HtmlInputText getFirstNameField() {
        return firstNameField;
    }

    public void setFirstNameField(HtmlInputText firstNameField) {
        this.firstNameField = firstNameField;
    }

	public boolean isInvalidPassword() {
		return invalidPassword;
	}

	public void setInvalidPassword(boolean invalidPassword) {
		this.invalidPassword = invalidPassword;
	}

	public boolean isInvalidPresentation() {
		return invalidPresentation;
	}

	public void setInvalidPresentation(boolean invalidPresentation) {
		this.invalidPresentation = invalidPresentation;
	}

    /**
     * Method called when the "Viewer" tab is selected on the front end pages
     */
    public void toggleRoleTypeViewer(ActionEvent ae) {
        parent.setRole(ParticipantInfo.ROLE_VIEWER);

        presentationPassword = "";

        if (firstNameField != null) {
            firstNameField.requestFocus();
        }
    }

    /**
     * Method called when the "Moderator" tab is selected on the front end
     * pages
     */
    public void toggleRoleTypeModerator(ActionEvent ae) {
        parent.setRole(ParticipantInfo.ROLE_MODERATOR);

        presentationName = "";
        presentationPassword = "";

        if (firstNameField != null) {
            firstNameField.requestFocus();
        }
    }

    /**
     * Method called when a presentation is selected in the front end page level
     * dropdown list
     *
     * @param event of the selection
     */
    public void selectPresentation(ValueChangeEvent event) {
        if (parent.isModerator()) {
            presentationName = "";
            return;
        }
    }

    /**
     * Method called when the user wishes to reset the fields on the login page
     * This will clear the UIComponent values, as well as variables
     *
     * @param ae of the reset
     */
    public void resetButton(ActionEvent ae) {
        UIComponent base = ae.getComponent();
        UIComponent parentForm = base.getParent();

        while (!(parentForm instanceof HtmlForm)) {
            parentForm = parentForm.getParent();
        }

        // Clear the various fields
        clearSingleField(parentForm, "firstName");
        clearSingleField(parentForm, "lastName");
        clearSingleField(parentForm, "email");
        clearSingleField(parentForm, "viewPassword");
        invalidPassword = false;
        invalidPresentation = false;
        clearSingleField(parentForm, "newPresentationName");
        clearSingleField(parentForm, "moderatorPassword");
        
        // Clear the select boxes
        clearSingleField(parentForm, "existingPresentationName");

        // Reset available variables
        clearFields();
        if (parent != null) {
            parent.clearFields();
        }

        // Request default focus
        if (firstNameField != null) {
            firstNameField.requestFocus();
        }
    }

    /**
     * Convenience method to reset the value of a UIInput component
     *
     * @param parent of the component to reset
     * @param id of the component to reset
     */
    private void clearSingleField(UIComponent parent, String id) {
        try {
            UIInput toClear = (UIInput)parent.findComponent(id);
            toClear.setSubmittedValue("");
        }catch (Exception ignored) {
            /* Intentionally ignored - if this fails the one value won't be cleared */
        }
    }

    /**
     * Method to reset the login fields
     */
    public void clearFields() {
        presentationName = "";
        presentationPassword = null;
    }
	
    public void validatePassword(ActionEvent ae){
    	if (ae.getSource() instanceof HtmlInputSecret) {
    	    HtmlInputSecret component = (HtmlInputSecret)ae.getSource();
    	    validatePassword((String)component.getValue());
    	}
    }
    
    public boolean validatePassword(String inputPassword){
    	setInvalidPassword(false);
        if ((presentationName != null) && (!presentationName.equals("")) &&
                (!presentationName.equals(PresentationManagerBean.DEFAULT_PRESENTATION))) {
        	// View password is invalid if it does not match the selected presentation.
        	if (!PresentationManager
                    .getInstance().isPasswordAndPresentationMatch(
                    inputPassword, getPresentationName())) {
        		setInvalidPassword(true);
                return false;
            }
        }
        return true;
    }
    
    public String getSelectedPresentationPassword(){
        if(PresentationManager.getInstance().getPresentation(presentationName)==null){
        	return null;
        }else{
        	 return PresentationManager.getInstance().getPresentation(presentationName).getPassword();
        }
    }
    
    public boolean validatePresentation(){
    	setInvalidPresentation(false);
        if ((presentationName == null) || (presentationName.equals("")) ||
                (presentationName.equals(PresentationManagerBean.DEFAULT_PRESENTATION))) {
        		setInvalidPresentation(true);
                return false;
        }
        return true;
    }

}

webmc/src/main/java/com/icesoft/faces/presenter/presentation/PresentationManagerBean.java
/*
 * Version: MPL 1.1/GPL 2.0/LGPL 2.1
 *
 * "The contents of this file are subject to the Mozilla Public License
 * Version 1.1 (the "License"); you may not use this file except in
 * compliance with the License. You may obtain a copy of the License at
 * http://www.mozilla.org/MPL/
 *
 * Software distributed under the License is distributed on an "AS IS"
 * basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
 * License for the specific language governing rights and limitations under
 * the License.
 *
 * The Original Code is ICEfaces 1.5 open source software code, released
 * November 5, 2006. The Initial Developer of the Original Code is ICEsoft
 * Technologies Canada, Corp. Portions created by ICEsoft are Copyright (C)
 * 2004-2006 ICEsoft Technologies Canada, Corp. All Rights Reserved.
 *
 * Contributor(s): _____________________.
 *
 * Alternatively, the contents of this file may be used under the terms of
 * the GNU Lesser General Public License Version 2.1 or later (the "LGPL"
 * License), in which case the provisions of the LGPL License are
 * applicable instead of those above. If you wish to allow use of your
 * version of this file only under the terms of the LGPL License and not to
 * allow others to use your version of this file under the MPL, indicate
 * your decision by deleting the provisions above and replace them with
 * the notice and other provisions required by the LGPL License. If you do
 * not delete the provisions above, a recipient may use your version of
 * this file under either the MPL or the LGPL License."
 *
 */
package com.icesoft.faces.presenter.presentation;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.Iterator;
import java.util.Map;

import javax.faces.model.SelectItem;

import org.icefaces.application.PushRenderer;

import com.icesoft.faces.presenter.participant.Participant;
import com.icesoft.faces.presenter.util.MessageBundleLoader;

/**
 * Class to handle the UI level representation of the presentation manager Looks
 * after things like the login screen presentation list, requesting addition of
 * new users to presentations, etc.
 */
public class PresentationManagerBean {
	public static final String DEFAULT_PRESENTATION = MessageBundleLoader
			.getMessage("bean.presentationManagerBean.defaultPresentation");
	private static final String NO_PRESENTATION = MessageBundleLoader
			.getMessage("bean.presentationManagerBean.noPresentation");

	private PresentationManager backendManager = PresentationManager
			.getInstance();
	private String currentPresentationsSelection = NO_PRESENTATION;

	public PresentationManagerBean() {
	}

	public String getCurrentPresentationsSelection() {
		return currentPresentationsSelection;
	}

	/**
	 * Method to get a named presentation from the back end manager
	 * 
	 * @param name
	 *            of the presentation
	 * @return the presentation, or null if it doesn't exist
	 */
	public Presentation getPresentation(String name) {
		return backendManager.getPresentation(name);
	}

	/**
	 * Method to get the default presentation selection text This is used for
	 * the initial state in dropdowns on the login screen
	 * 
	 * @return DEFAULT_PRESENTATION string
	 */
	public String getDefaultPresentationSelection() {
		return DEFAULT_PRESENTATION;
	}

	/**
	 * Method to get the list of presentations as a SelectItem list. This
	 * basically wraps the back end list. In addition this will create default
	 * initial presentations as needed These initial presentations are loaded
	 * automatically and run in slide show mode, and can be used to provide a
	 * generic set of presentations that any user can join (so a deployment
	 * could include a "Howto" presentation, etc.) To setup a default
	 * presentation, just drop the proper zip file (normally the type that would
	 * be uploaded to webmc by a moderator) into the
	 * AutoPresentation.PRESENTATION_FOLDER_NAME folder, which is located
	 * normally in .../web/basepres/ Any files found in this folder will be
	 * loaded by AutoPresentation.createDefaultPresentation as a new
	 * presentation (name based on the file), with a password of 'password'
	 * 
	 * @return the presentations as SelectItems
	 */
	public SelectItem[] getPresentationItems() {
		Map presentations = backendManager.getPresentationMap();

		if (presentations.isEmpty()) {
			AutoPresentation.createDefaultPresentation(this);

			if (presentations.isEmpty()) {
				currentPresentationsSelection = NO_PRESENTATION;
				return new SelectItem[] { new SelectItem(NO_PRESENTATION) };
			}
		}

		Iterator presIter = presentations.keySet().iterator();
		ArrayList presentationNames = new ArrayList(presentations.size());
		//presentationNames.add(new SelectItem(DEFAULT_PRESENTATION));

		Presentation current;
		while (presIter.hasNext()) {
			current = (Presentation) presentations
					.get((String) presIter.next());
			if (!current.getName().equals("extracted"))
				presentationNames.add(new SelectItem(current.getName()));
		}

		// Sort the collection so we have some order in the presentation list
		Collections.sort(presentationNames, new SelectItemComparator());

		// Put the default at the top of the list
		presentationNames.add(0,new SelectItem(DEFAULT_PRESENTATION));
				
		//currentPresentationsSelection = DEFAULT_PRESENTATION;
		return (SelectItem[]) presentationNames
				.toArray(new SelectItem[presentationNames.size()]);
	}

	/**
	 * Method to create a new presentation This relies on the back end manager
	 * to do the real work, besides handing off the local renderer
	 * 
	 * @param participant
	 *            who created the presentation
	 * @param name
	 *            of the presentation to create
	 * @return the created presentation, or null if something went wrong
	 */
	public Presentation createPresentation(Participant participant, String name) {
		Presentation toReturn = backendManager.createPresentation(participant,
				name);

		if (toReturn != null) {
			toReturn.setManager(this);
		}
		// The presentation list should be updated.
		PushRenderer.render("loginPage");

		return toReturn;
	}

	/**
	 * Method to add a participant to a presentation The presentation should
	 * exist first before attempting to add to it
	 * 
	 * @param participant
	 *            to add to the presentation
	 * @param presentation
	 *            to join
	 */
	public void joinPresentation(Participant participant,
			Presentation presentation) {
		backendManager.joinPresentation(participant, presentation);
	}

	/**
	 * Method to end a presentation, such as when the moderator logs out
	 * Basically deletes the presentation from the list, and renders the login
	 * screen
	 * 
	 * @param presentation
	 *            to remove
	 */
	public void endPresentation(Presentation presentation) {
		backendManager.removePresentation(presentation);
		// The presentation list should be updated.
		PushRenderer.render("loginPage");
	}
	
	public class SelectItemComparator implements Comparator<SelectItem> {  
	    public int compare(SelectItem s1, SelectItem s2) {  
	        return s1.getLabel().compareTo(s2.getLabel());  
	    }  
	}  
}

webmc/WebContent/WEB-INF/inc/footer.xhtml
<!--
  ~ Version: MPL 1.1/GPL 2.0/LGPL 2.1
  ~
  ~ "The contents of this file are subject to the Mozilla Public License
  ~ Version 1.1 (the "License"); you may not use this file except in
  ~ compliance with the License. You may obtain a copy of the License at
  ~ http://www.mozilla.org/MPL/
  ~
  ~ Software distributed under the License is distributed on an "AS IS"
  ~ basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
  ~ License for the specific language governing rights and limitations under
  ~ the License.
  ~
  ~ The Original Code is ICEfaces 1.5 open source software code, released
  ~ November 5, 2006. The Initial Developer of the Original Code is ICEsoft
  ~ Technologies Canada, Corp. Portions created by ICEsoft are Copyright (C)
  ~ 2004-2006 ICEsoft Technologies Canada, Corp. All Rights Reserved.
  ~
  ~ Contributor(s): _____________________.
  ~
  ~ Alternatively, the contents of this file may be used under the terms of
  ~ the GNU Lesser General Public License Version 2.1 or later (the "LGPL"
  ~ License), in which case the provisions of the LGPL License are
  ~ applicable instead of those above. If you wish to allow use of your
  ~ version of this file only under the terms of the LGPL License and not to
  ~ allow others to use your version of this file under the MPL, indicate
  ~ your decision by deleting the provisions above and replace them with
  ~ the notice and other provisions required by the LGPL License. If you do
  ~ not delete the provisions above, a recipient may use your version of
  ~ this file under either the MPL or the LGPL License."
  ~
-->
<table xmlns="http://www.w3.org/1999/xhtml"
       xmlns:ice="http://www.icesoft.com/icefaces/component"
       class="height100" 
       width="100%"
       border="0" 
       cellspacing="0" 
       cellpadding="0">
    <tr>
        <td align="left" class="footerText" style="padding: 36px 0 0 30px;">
            <strong><ice:outputText value="&amp;copy;" escape="false" /> COPYRIGHT 2011</strong> 
            <a href="http://www.icesoft.com/" class="linkOrange">ICESOFT TECHNOLOGIES INC.</a>
        </td>
        <td align="right" class="footerText" style="padding: 36px 20px 0 0;">
            POWERED BY <ice:outputText value="&amp;nbsp;" escape="false" />
            <a href="http://www.icefaces.org" class="linkOrange">
                <strong>ICEfaces</strong>
            </a>
        </td>
        <td align="right" width="121">
            <img src="resources/images/footer_faces.jpg" alt="Powered by ICEfaces" width="121" height="95" />
        </td>
    </tr>
</table>

webmc/WebContent/WEB-INF/inc/login.xhtml
<!DOCTYPE HTML PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
                      "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<!--
  ~ Version: MPL 1.1/GPL 2.0/LGPL 2.1
  ~
  ~ "The contents of this file are subject to the Mozilla Public License
  ~ Version 1.1 (the "License"); you may not use this file except in
  ~ compliance with the License. You may obtain a copy of the License at
  ~ http://www.mozilla.org/MPL/
  ~
  ~ Software distributed under the License is distributed on an "AS IS"
  ~ basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
  ~ License for the specific language governing rights and limitations under
  ~ the License.
  ~
  ~ The Original Code is ICEfaces 1.5 open source software code, released
  ~ November 5, 2006. The Initial Developer of the Original Code is ICEsoft
  ~ Technologies Canada, Corp. Portions created by ICEsoft are Copyright (C)
  ~ 2004-2006 ICEsoft Technologies Canada, Corp. All Rights Reserved.
  ~
  ~ Contributor(s): _____________________.
  ~
  ~ Alternatively, the contents of this file may be used under the terms of
  ~ the GNU Lesser General Public License Version 2.1 or later (the "LGPL"
  ~ License), in which case the provisions of the LGPL License are
  ~ applicable instead of those above. If you wish to allow use of your
  ~ version of this file only under the terms of the LGPL License and not to
  ~ allow others to use your version of this file under the MPL, indicate
  ~ your decision by deleting the provisions above and replace them with
  ~ the notice and other provisions required by the LGPL License. If you do
  ~ not delete the provisions above, a recipient may use your version of
  ~ this file under either the MPL or the LGPL License."
  ~
-->
<div xmlns="http://www.w3.org/1999/xhtml"
     xmlns:h="http://java.sun.com/jsf/html"
     xmlns:f="http://java.sun.com/jsf/core"
     xmlns:ice="http://www.icesoft.com/icefaces/component"
     class="backgroundTop">
<div class="backgroundBottom">
<center>
<div class="loginBox">
<ice:form id="loginForm">
    <ice:graphicImage value="#{participant.mobile?'./resources/images/login_logo_mobile.gif':'./resources/images/login_logo.gif'}" 
                      alt="#{msgs['page.login.loginLogo.alt']}"
                      styleClass="loginLogo" />
    <!-- Viewer and Moderator Tabs for Desktop Browsers -->
    <ice:panelGroup rendered="#{!participant.mobile}"
                    style="text-align: left;">
	    <ice:panelGroup styleClass="moderatorViewerButtons">
	        <ice:commandButton id="viewerBtn"
	                actionListener="#{participant.loginBean.toggleRoleTypeViewer}"
	                alt="#{msgs['page.login.viewerButton.alt']}"
	                immediate="true"
	                image="resources/images/login_tab_view_#{not participant.moderator}.gif"/>
	        <ice:commandButton id="moderatorBtn"
	                actionListener="#{participant.loginBean.toggleRoleTypeModerator}"
	                alt="#{msgs['page.login.moderatorButton.alt']}"
	                immediate="true"
	                image="resources/images/login_tab_mod_#{participant.moderator}.gif"/>
	    </ice:panelGroup>
	</ice:panelGroup>
	<!-- Desktop and Mobile browsers have a different layout that is triggered 
	     with the rendered attribute on each "cell" of the panelGrid -->	
	<ice:panelGrid columns="4"
	               cellspacing="0"
	               cellpadding="0"
                   styleClass="loginPanelGrid" 
	               columnClasses="loginFirstColumn,loginSecondColumn,loginThirdColumn,loginFourthColumn">
        <!-- Empty Cell -->
        <ice:panelGroup rendered="#{participant.mobile}" />
        <!-- Name common to both Viewer and Moderator -->
        <ice:panelGroup>       
            <ice:outputLabel styleClass="loginLabel firstNameLabel"
                             value="#{msgs['page.login.nameLabel']} " 
                             for="firstName" />
            <ice:inputText id="firstName"
                           value="#{participant.firstName}"
                           converter="fixCaps" 
                           required="true"
                           partialSubmit="true" 
                           maxlength="20"
                           tabindex="1"
                           styleClass="loginInput"
                           binding="#{participant.loginBean.firstNameField}"/>
        </ice:panelGroup>
        <!-- Name error message -->
        <ice:panelGroup>
            <ice:message for="firstName" id="firstNameErr"
                         errorClass="inputError"/>
        </ice:panelGroup >
        <!-- Empty Cell -->
        <ice:panelGroup rendered="#{participant.mobile}" />
        <!-- Empty Cell -->
        <ice:panelGroup rendered="#{participant.mobile}" />
        <!-- Viewer selects from presentations -->
        <ice:panelGroup rendered="#{not participant.moderator}">
            <ice:outputLabel styleClass="loginLabel"
                             value="#{msgs['page.login.presentationLabel']} "
                             for="existingPresentationName"/>
            <ice:selectOneMenu id="existingPresentationName"
                               partialSubmit="true"
                               tabindex="4"
                               value="#{participant.loginBean.presentationName}"
                               styleClass="presentationMenu"
                               valueChangeListener="#{participant.loginBean.selectPresentation}">
                <f:selectItems value="#{presentationMgr.presentationItems}"/>
            </ice:selectOneMenu>
        </ice:panelGroup>
        <!-- Moderator creates a new presentation -->
        <ice:panelGroup rendered="#{participant.moderator and not participant.mobile}">
            <ice:outputLabel styleClass="loginLabel"
                             value="#{msgs['page.login.presentationLabel']} "
                             for="newPresentationName"/>
            <ice:inputText id="newPresentationName"
                           required="true"
                           maxlength="50"
                           tabindex="4"
                           styleClass="loginInput"
                           value="#{participant.loginBean.presentationName}"
                           partialSubmit="true">
                <f:validator validatorId="NameValidator"/>
            </ice:inputText>
        </ice:panelGroup>
        <!-- Viewer Presentation Error Message -->
        <ice:panelGroup rendered="#{not participant.moderator}">
            <ice:outputText id="presentationErr"
                            value="#{msgs['page.login.presentationError.required']}"
                            rendered="#{participant.loginBean.invalidPresentation}"
                            styleClass="inputError"/>
        </ice:panelGroup>
        <!-- Empty Cell -->
        <ice:panelGroup rendered="#{participant.mobile}" />
        <!-- Moderator Presentation Error Message -->
        <ice:panelGroup rendered="#{participant.moderator and not participant.mobile}">
            <ice:message for="newPresentationName" id="newPresentationNameErr"
                         errorClass="inputError"/>
        </ice:panelGroup>
        <!-- Empty Cell -->
        <ice:panelGroup rendered="#{!participant.mobile}" /> 
        <!-- Viewer inputs password -->
        <ice:panelGroup rendered="#{not participant.moderator}" >
            <!-- Empty Cell when password not required -->
	        <ice:panelGroup rendered="#{empty participant.loginBean.selectedPresentationPassword}" />
            <ice:outputLabel rendered="#{not empty participant.loginBean.selectedPresentationPassword}"
                             styleClass="loginLabel passwordLabel"
                             value="#{msgs['page.login.passwordLabel']} "
                             for="viewPassword" />
            <ice:inputSecret id="viewPassword"
                             rendered="#{not empty participant.loginBean.selectedPresentationPassword}"
                             value="#{participant.loginBean.presentationPassword}"
                             tabindex="5"
                             redisplay="true" 
                             partialSubmit="true"
                             maxlength="20"
                             styleClass="loginInput"
                             actionListener="#{participant.loginBean.validatePassword}">
            </ice:inputSecret>
        </ice:panelGroup>
        <!-- Moderator inputs password -->
        <ice:panelGroup rendered="#{participant.moderator and not participant.mobile}">
	        <ice:outputLabel styleClass="loginLabel"
	                         value="#{msgs['page.login.passwordLabel']} "
	                         for="moderatorPassword" />
	        <ice:inputSecret id="moderatorPassword"
	                         value="#{participant.loginBean.presentationPassword}"
	                         maxlength="20"
	                         tabindex="5"
	                         styleClass="loginInput"
	                         redisplay="true" >
	        </ice:inputSecret>
        </ice:panelGroup>
        <!-- Viewer Password Error Message -->
        <ice:panelGroup rendered="#{not participant.moderator}" >
	        <ice:outputText id="viewerPasswordErr"
                              value="#{msgs['page.login.passwordError.invalid']} "
	                        rendered="#{participant.loginBean.invalidPassword}"
	                        styleClass="inputError"/>
        </ice:panelGroup>
        <!-- Moderator Password Error Message -->
        <ice:panelGroup rendered="#{participant.moderator and not participant.mobile}">
	        <ice:message for="moderatorPassword" id="moderatorPasswordErr"
	                     errorClass="inputError"/>
        </ice:panelGroup>
        <!-- Empty Cell -->
        <ice:panelGroup />
        <!-- Empty Cell -->
        <ice:panelGroup />
        <!-- Viewer Buttons -->
        <ice:panelGroup rendered="#{not participant.moderator}"
	                    styleClass="loginButtons">
            <ice:commandButton id="vResetBtn"
                               image="resources/images/butt_reset.gif"
                               actionListener="#{participant.loginBean.resetButton}"
                               immediate="true"
                               tabindex="6"
                               alt="#{msgs['page.login.resetButton.alt']}" />
            <ice:commandLink   id="vLoginBtn"
                               action="#{participant.login}"
                               tabindex="7"
                               alt="#{msgs['page.login.joinLink.alt']}">
                <ice:graphicImage value="resources/images/butt_join_present.gif" 
                                  style="border: 0; "/>
                <f:param name="loginSource" 
                         value="viewLogin"/>
            </ice:commandLink>
	    </ice:panelGroup>
	    <!-- Moderator Buttons -->
	    <ice:panelGroup rendered="#{participant.moderator and not participant.mobile}"
	                    styleClass="loginButtons">
            <ice:commandButton id="mResetBtn"
                               image="resources/images/butt_reset.gif"
                               actionListener="#{participant.loginBean.resetButton}"
                               immediate="true"
                               tabindex="7"
                               alt="#{msgs['page.login.resetButton.alt']}"/>
            <ice:commandLink   id="mLoginBtn"
                               action="#{participant.login}"
                               tabindex="8"
                               alt="#{msgs['page.login.startLink.alt']}">
                <ice:graphicImage value="resources/images/butt_start_present.gif"
                                  style="border: 0;"/>
                <f:param name="loginSource" 
                         value="moderatorLogin"/>
            </ice:commandLink>
	    </ice:panelGroup>
        <!-- Empty Cell -->
        <ice:panelGroup rendered="#{!participant.mobile}" />
    </ice:panelGrid>
	<!-- Moderator Instructions -->
    <ice:panelGroup styleClass="headerMessage" 
                    rendered="#{participant.moderator and not participant.mobile}">
	    <ice:outputText value="#{msgs['page.login.moderator.instruction']}" />
	    <br />
	    <ice:outputText value="#{msgs['page.login.moderator.instruction.password']}"/>
    </ice:panelGroup>
    <!-- Viewer Instructions -->
    <ice:panelGroup styleClass="headerMessage" 
                    rendered="#{not participant.moderator and not participant.mobile}">
        <ice:outputText value="#{msgs['page.login.viewer.instruction']}"/>
        <br />
        <ice:outputText value="#{msgs['page.login.viewer.instruction.password']}"/>
    </ice:panelGroup>
	
</ice:form>
</div>
</center>
</div>
</div>